### ISSUE TITLE
Provide evals for OpenAI to help with code input models

### ISSUE THREAD

**Issue by rgbkrk** [rgbkrk/chatlab#44]
When using chatlab's builtin ipython setup, sometimes the model tries to call the function with bad JSON.

![image](https://github.com/rgbkrk/chatlab/assets/836375/cb36c6cc-7d6c-4563-be76-860bcb8ec2eb)

Task: Determine how we can submit these as examples using [OpenAI Evals](https://github.com/openai/evals).

-----

For more on this, check out the OpenAI community forums: https://community.openai.com/t/plaintext-schemas-for-chat-functions/275750?u=rgbkrk

**Comment by CarlsonCarlson** [comment]
Awesome!

**Comment by rgbkrk** [comment]
Going to close this as the latest models have gotten _very_ good for function calling.
