### ISSUE TITLE
Add temperature to openai.ChatCompletion.create

### ISSUE THREAD

**Issue by khaimt** [rgbkrk/chatlab#90]
-   ChatLab version:1.0.0a25
-   Python version:3.10
-   Operating System:

### Description

I think we should allow to set temperature in [openai.ChatCompletion.create ](https://github.com/rgbkrk/chatlab/blob/main/chatlab/conversation.py#L263). And the default value for temperature should be 0, as this is function calling, the response should be stable and consistent.

### What I Did
We can add: ** kwargs to def submit and get temperature from **kwargs
```
resp = openai.ChatCompletion.create(
                model=self.model,
                messages=full_messages,
                **self.function_registry.api_manifest(),
                stream=stream,
                temperature=kwargs.get("temperature", 0),
            )
```

**Comment by rgbkrk** [comment]
I support that. Would you be able to make a PR? I'd love the contribution.

**Comment by khaimt** [comment]
@rgbkrk Sure, please give me the permission !

**Comment by rgbkrk** [comment]
You'll have to create a Fork and submit a PR. I recommend reading through https://docs.github.com/en/get-started/quickstart/contributing-to-projects

**Comment by khaimt** [comment]
@rgbkrk I have just raised a PR: https://github.com/rgbkrk/chatlab/pull/91

**Comment by rgbkrk** [comment]
Done and shipped! Thank you!
